GET http://localhost:3000/users/

###
POST  http://localhost:3000/users/new
Content-Type: application/json
 
{
    "name": "Kyle",
    "username": "Martin",
    "password": "123"
}


###
PATCH  http://localhost:3000/users/63b896a562c3e252d9232a5a
Content-Type:  application/json

{
    "username": "LJ23"
}

###
DELETE http://localhost:3000/users/63b961d63fcea0bb2f028d69

###
GET http://localhost:3000/users/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcnRpbkwiLCJpYXQiOjE2NzM1MjcwMzB9.eoPrtWwQtNuneFPg6D5arbsaC3Vqhcem2ZYZnqcapBk

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Martin",
    "password": "123"
}